name: Docker Build and Publish

on:
  push:
    branches: [ main, dev ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Docker tags
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          # For main branch
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          type=sha,enable=${{ github.ref == 'refs/heads/main' }}
          # For dev branch
          type=raw,value=dev,enable=${{ github.ref == 'refs/heads/dev' }}
          type=sha,prefix=dev-,enable=${{ github.ref == 'refs/heads/dev' }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

